fos_rest:
    view:
        view_response_listener: true
    body_listener:
        enabled: true
    format_listener:
        rules:
            - { host: api.renaissance-terrehappy.fr, path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json ]}
            - { host: renaissance-terrehappy.fr, path: ^/, priorities: [ html ], fallback_format: html }
