swiftmailer:
    delivery_addresses: ['patricia.bergez@gmail.com']
    transport: smtp
    encryption: ssl
    host: smtp.gmail.com
    username: patricia.bergez@gmail.com
    password: biotech33
    spool: { type: 'memory' }
