to_ng:
    path: /
    host: 'renaissance-terrehappy.fr'
    defaults:
        url: 'https://renaissance-terrehappy.fr'

controllers:
    host: 'admin.renaissance-terrehappy.fr'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.renaissance-terrehappy.fr'
    path: /login_check
    methods: [POST]

api_controllers:
    host: 'api.renaissance-terrehappy.fr'
    resource: ../../src/ApiController
    type: annotation
