#index:
#    path: /
#    controller: App\Controller\DefaultController::index
accueil_homepage:
    path: /
    defaults: {_templates: default: index.html.twig }

product_homepage:
    path: /product
    defaults: {_templates: product: index.html.twig }

category_homepage:
    path: /category
    defaults: {_templates: category: index.html.twig }

actu_homepage:
    path: /actu
    defaults: {_templates: actu: index.html.twig }

indication_homepage:
    path: /indication
    defaults: {_templates: indication: index.html.twig }

calendar_homepage:
    path: /calendar
    defaults: {_templates: calendar: index.html.twig }

daypart_homepage:
    path: /daypart
    defaults: {_templates: daypart: index.html.twig }

typeconsult_homepage:
    path: /typeconsult
    defaults: {_templates: typeconsult: index.html.twig }

user_homepage:
    path: /user
    defaults: {_templates: user: index.html.twig }
